EPROCURENTWEB/Controllers/AltaProveedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EprocurementWeb.Business;
using EPROCUREMENT.GAPPROVEEDOR.Entities;
using EPROCUREMENT.GAPPROVEEDOR.Entities.Proveedor;
using System.IO;
using EprocurementWeb.Filters;
using Newtonsoft.Json;
using System.Web.Script.Serialization;
using EprocurementWeb.Models;

namespace EprocurementWeb.Controllers
{
    public class AltaProveedorController : Controller
    {
        public ProveedorInformacionFinanciera cuenta = null;
        public List<ProveedorCuentaDTO>  ProveedorCuentaListRegistro = new List<ProveedorCuentaDTO>();
        public ActionResult InformacionBF()
        {
            ViewBag.Respuesta = "";
            ViewBag.MenssageError = EprocurementWeb.GlobalResources.RHome.Message_Error_Required_Generic;
            ViewBag.MenssageErrorAirPort = EprocurementWeb.GlobalResources.RHome.Message_Error_Required_Airport;
            ViewBag.MenssageErrorDocument = EprocurementWeb.GlobalResources.RHome.Message_Error_Required_Document;
            var usuarioInfo = new ValidaSession().ObtenerUsuarioSession();
            ViewBag.UsuarioInfo = usuarioInfo;
            var idProveedor = 0;
            if (usuarioInfo != null)
            {
                idProveedor = usuarioInfo.IdProveedor;
            }
            Session["IdProveedor"] = idProveedor;
            BusinessLogic business = new BusinessLogic();

            if (usuarioInfo.IdEstatus == 5 || usuarioInfo.IdEstatus == 7)
            {
                ProveedorCuentaRequestDTO proveedorCuentaRequest = new ProveedorCuentaRequestDTO
                {
                    IdProveedor = idProveedor
                };
                var proveedorCuentaResponse = business.GetProveedorCuentaList(proveedorCuentaRequest);
                //ProveedorCuentaRequestDTO proveedorCuentaAeropuertoRequest = new ProveedorCuentaRequestDTO
                //{
                //    ProveedorCuentaList = proveedorCuentaResponse.ProveedorCuentaList
                //};
                //var proveedorCuentaAeropuertoResponse = business.GetProveedorCuentaAeropuertoList(proveedorCuentaAeropuertoRequest);
                ViewBag.ProveedorCuentaList = proveedorCuentaResponse.ProveedorCuentaList;

                ProveedorDocumentoRequestDTO proveedorDocumentoRequest = new ProveedorDocumentoRequestDTO
                {
                    IdProveedor = idProveedor
                };

                var proveedorDocumentoResponse = business.GetProveedorDocumentoList(proveedorDocumentoRequest);
                ViewBag.ProveedorDocumentoList = proveedorDocumentoResponse.ProveedorDocumentoList;
            }

            Session["ProveedorCuentaListRegistro"] = new List<ProveedorCuentaDTO>();
            var aeropuertos = business.GetAeropuertosList();
            ViewBag.BancoList = business.GetBancoList();
            ViewBag.TipoCuentaList = business.GetTipoCuentaList();
            ProveedorDetalleRequestModel request = new ProveedorDetalleRequestModel();
            request.IdProveedor = idProveedor;
            var response = business.GetProveedorElemento(request).Proveedor;
            var aeropuertosAsignados = response.EmpresaList;
            var proveedorDocumento = business.GetCatalogoDocumentoList();
            var formatoDocumento = business.GetFormatoArchivoList();
            if (cuenta == null)
            {
                cuenta = new ProveedorInformacionFinanciera();
                cuenta.ProveedorCuentaList = new List<ProveedorCuentaDTO> { new ProveedorCuentaDTO { Cuenta = null, IdBanco = 0, CLABE = null, IdTipoCuenta = 0, IdProveedor = idProveedor } };
            }
            cuenta.RFC = response.RFC;
            cuenta.ProveedorCuentaList[0].AeropuertoList = (from aeropuerto in aeropuertos
                                                            join aeropuertoA in aeropuertosAsignados on aeropuerto.Id equals aeropuertoA.IdCatalogoAeropuerto
                                                            select new AeropuertoDTO { Id = aeropuerto.Id, Nombre = aeropuerto.Nombre, Checado = false }).ToList();
            cuenta.CatalogoDocumentoList = proveedorDocumento;
            cuenta.ProveedorCuentaListRegistro = new List<ProveedorCuentaDTO>();
            cuenta.CuentaBancaria = new ProveedorCuentaDTO();
            cuenta.CuentaBancaria.AeropuertoList = cuenta.ProveedorCuentaList[0].AeropuertoList;
            
            Session["ProveedorCuentaListRegistro"] = new List<ProveedorCuentaDTO>();
            return View(cuenta);
        }

        public ActionResult AgregarCuenta(ProveedorInformacionFinanciera cuenta)
        {
            ViewBag.Respuesta = "";
            BusinessLogic business = new BusinessLogic();
            var bancoList = business.GetBancoList();
            var tipoCuentaList = business.GetTipoCuentaList();
            ProveedorCuentaListRegistro = new ValidaSession().RecuperaRegistrosSession();
            if (cuenta.ProveedorCuentaListRegistro == null)
            {
                cuenta.ProveedorCuentaListRegistro = new List<ProveedorCuentaDTO>();
            }
            if (ProveedorCuentaListRegistro == null)
            {
                ProveedorCuentaListRegistro = new List<ProveedorCuentaDTO>();
            }
            if (cuenta.ProveedorCuentaList != null && cuenta.ProveedorCuentaList.Count > 0)
            {
                cuenta.ProveedorCuentaList.First().AeropuertoList = cuenta.ProveedorCuentaList.First().AeropuertoList.Where(x => x.Checado).ToList();
                ProveedorCuentaListRegistro.Add(cuenta.ProveedorCuentaList.First());
            }
            Session["ProveedorCuentaListRegistro"] = ProveedorCuentaListRegistro;
            foreach(var registro in ProveedorCuentaListRegistro)
            {
                registro.NombreBanco = bancoList.FirstOrDefault(x => x.IdBanco == registro.IdBanco).Nombre;
                registro.TipoCuenta = tipoCuentaList.FirstOrDefault(x => x.IdTipoCuenta == registro.IdTipoCuenta).Tipo;
            }
            cuenta.ProveedorCuentaListRegistro = ProveedorCuentaListRegistro;
            var aeropuertos = business.GetAeropuertosList();
            ViewBag.BancoList = bancoList;
            ViewBag.TipoCuentaList = tipoCuentaList;
            ProveedorDetalleRequestModel request = new ProveedorDetalleRequestModel();
            if (cuenta.ProveedorCuentaList != null)
            {
                request.IdProveedor = cuenta.ProveedorCuentaList.First().IdProveedor;
            }
            var response = business.GetProveedorElemento(request).Proveedor;
            var aeropuertosAsignados = response.EmpresaList;
            var proveedorDocumento = business.GetCatalogoDocumentoList();
            var formatoDocumento = business.GetFormatoArchivoList();
            if (cuenta == null)
            {
                cuenta = new ProveedorInformacionFinanciera();                
            }
            cuenta.ProveedorCuentaList = new List<ProveedorCuentaDTO> { new ProveedorCuentaDTO { Cuenta = null, IdBanco = 0, CLABE = null, IdTipoCuenta = 0, IdProveedor = cuenta.ProveedorCuentaList.First().IdProveedor } };
            cuenta.RFC = response.RFC;
            cuenta.ProveedorCuentaList[0].AeropuertoList = (from aeropuerto in aeropuertos
                                                            join aeropuertoA in aeropuertosAsignados on aeropuerto.Id equals aeropuertoA.IdCatalogoAeropuerto
                                                            select new AeropuertoDTO { Id = aeropuerto.Id, Nombre = aeropuerto.Nombre, Checado = false }).ToList();
            foreach(var aeropuerto in cuenta.ProveedorCuentaList[0].AeropuertoList)
            {
                foreach(var reg in ProveedorCuentaListRegistro)
                {
                    if(reg.AeropuertoList.Exists(x => x.Id == aeropuerto.Id && x.Checado))
                    {
                        aeropuerto.Agregado = true;
                        break;
                    }
                }
                aeropuerto.Checado = false;
            }
            
            cuenta.CatalogoDocumentoList = proveedorDocumento;
            //cuenta.ProveedorCuentaListRegistro = new List<ProveedorCuentaDTO>();
            cuenta.CuentaBancaria = new ProveedorCuentaDTO();
            cuenta.CuentaBancaria.AeropuertoList = cuenta.ProveedorCuentaList[0].AeropuertoList;

            return View("InformacionBF", cuenta);
        }

        [HttpPost]
        public ActionResult Upload()
        {
            var usuarioInfo = new ValidaSession().ObtenerUsuarioSession();
            // Logica anterior
            BusinessLogic business = new BusinessLogic();
            var proveedorDocumento = business.GetCatalogoDocumentoList();
            int idProveedor = new ValidaSession().RecuperaIdProveedorSession();
            var aeropuertos = business.GetAeropuertosList();
            ViewBag.BancoList = business.GetBancoList();
            ViewBag.TipoCuentaList = business.GetTipoCuentaList();
            List<ProveedorDocumentoDTO> provDoctos = new List<ProveedorDocumentoDTO>();

            string cuentaJson = Request["cuenta"];
            if(cuentaJson.Length > 0)
            {
                var cuenta = (ProveedorInformacionFinanciera)JsonConvert.DeserializeObject(cuentaJson, typeof(ProveedorInformacionFinanciera));

                for(int i = 0; i < cuenta.ProveedorCuentaListRegistro.Count; i++)
                {
                    cuenta.ProveedorCuentaListRegistro[i].IdProveedor = idProveedor;
                }

                int contador = Request.Files.Count;
                cuenta.CatalogoDocumentoList = new List<CatalogoDocumentoDTO>();
                bool extensionesValidas = true;


EPROCURENTWEB/Views/AltaProveedor/DocumentacionBF.cshtml
@model EPROCUREMENT.GAPPROVEEDOR.Entities.Proveedor.ProveedorInformacionFinanciera


@{
    ViewBag.Title = "Documentación";
}

<link href="~/Content/validacionProveedor.css" rel="stylesheet" />
<div class="row panel-header">
    <div class="col-sm-4 pull-left">
        <img class="gap-logo" src="@Url.GetImage("logo-gap-color.png",false)" />
    </div>

    <div class="col-sm-4 t-a-c ">
        <h1 class="h-title">
            @RHome.ProvP
        </h1>
    </div>

    <div class="col-sm-4">
        <ul class="pull-right" style="list-style:none; float: right; display:none;">
            <li style="display:inline;">
                <a href="" class="setLang" data-lang="es-MX"><img src="@Url.GetImage("Mexico.png",false)" /></a>
            </li>
            <li style="display:inline;">
                <a href="" class="setLang" data-lang="en-US"><img src="@Url.GetImage("usa.png", false)" /></a>
            </li>
        </ul>
    </div>
</div>

<div class="container">
    <div class="row pb-0">
        <div class="col-sm-12">
            <h3 class="subtitle">
                @RHome.TitlePP
            </h3>
        </div>
    </div>

    @using (Html.BeginForm("DocumentacionBF", "AltaProveedor", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        @Html.HiddenFor(m => m.RFC)
        <div class="formPrincipal">
            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item" style="width:50%">
                    <a class="nav-link active" href="#IF" role="tab" data-toggle="tab">Información Financiera</a>
                </li>
            </ul>
            <div class="tab-content" style="background-color:white; padding: 15px;">
                <div role="tabpanel" class="tab-pane fade in active show" id="IF">
                    <div class="col100">
                        @for (int idx = 0; idx < Model.CatalogoDocumentoList.Count; idx++)
                        {
                            <div class="col100">
                                <div class="col25">
                                    <div class="inputIF">
                                        @Html.LabelFor(m => m.CatalogoDocumentoList[idx].NombreDocumento, new { @class = "labelTexto control-label" })
                                        @Html.HiddenFor(m => m.CatalogoDocumentoList[idx].RutaDocumento)
                                    </div>
                                </div>
                                <div class="col25">
                                    @Html.ActionLink("Descargar", "DescargarArchivo", new { ruta = Model.CatalogoDocumentoList[idx].RutaDocumento, nombre = Model.CatalogoDocumentoList[idx].NombreDocumento })
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <hr />
            </div>

            <div class="row mt-4">
                <div class="col-sm-6">&nbsp;</div>
                <div class="col-sm-3"><input type="button" value="Cancelar" class="btnStyle btnWhite" /></div>
                <div class="col-sm-3"><input type="submit" value="Enviar" class="btnStyle" /></div>
            </div>
        </div>

    }
</div>