EPROCURENTWEB/Controllers/GestionController.cs
using EprocurementWeb.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EprocurementWeb.Models;
using EprocurementWeb.Filters;
using EPROCUREMENT.GAPPROVEEDOR.Entities;
using System.IO;
using System.Text;
using System.Web.UI.WebControls;
using System.Web.UI;
using OfficeOpenXml;
using System.Data;
using DocumentFormat.OpenXml.Spreadsheet;
using System.Xml.Schema;
using System.Configuration;
using System.Net.Http;
using System.Xml;
using System.Xml.Serialization;
using System.Xml.Linq;
using EprocurementWeb.SatServiceReference;

namespace EprocurementWeb.Controllers
{
    public class GestionController : Controller
    {
        public List<AeropuertoListaDTO> AeropuertoList;
        public string nav_factura;
        public string nav_sFactura;
        public string nav_sCotizacion;
        public string nav_sOC;
        // GET: Gestion
        public ActionResult Index()
        {
            GetAeropuertoList();
            ViewBag.AeropuertoList = AeropuertoList;
            
            //var aa = GetFacturaList(null, null, null, null, null, null, null);
            return View();
        }


        // GET: SolicitudFacturacion
        public ActionResult SolicitudFacturacion()
        {
            var usuarioInfo = new ValidaSession().ObtenerUsuarioSession();
            ViewBag.TipoEmpresa = usuarioInfo.TipoEmpresa;
            List<EstatusSolicitudModel> estatusList = new List<EstatusSolicitudModel>();
            estatusList.Add(new EstatusSolicitudModel { IdEstatus = 1, Descripcion = "Pendiente" });
            estatusList.Add(new EstatusSolicitudModel { IdEstatus = 2, Descripcion = "En Proceso" });
            estatusList.Add(new EstatusSolicitudModel { IdEstatus = 3, Descripcion = "Aceptada" });
            estatusList.Add(new EstatusSolicitudModel { IdEstatus = 4, Descripcion = "Cancelada por AX" });
            estatusList.Add(new EstatusSolicitudModel { IdEstatus = 5, Descripcion = "Pagada" });
            ViewBag.EstatusSolicitudList = estatusList;

            List<SolicitudFactura> numeroSolicitudList = new List<SolicitudFactura>();
            numeroSolicitudList.Add(new SolicitudFactura { IdSolicitudFactura = 4 });
            numeroSolicitudList.Add(new SolicitudFactura { IdSolicitudFactura = 5 });
            numeroSolicitudList.Add(new SolicitudFactura { IdSolicitudFactura = 6 });
            numeroSolicitudList.Add(new SolicitudFactura { IdSolicitudFactura = 7 });
            ViewBag.NumeroSolicitudList = numeroSolicitudList;


            return View();
        }

        // GET: SolicitudFacturacion
        public ActionResult SolicitudDetalle(int idSolicitudFactura)
        {
            ViewBag.IdSolicitudFactura = idSolicitudFactura;
            var usuarioInfo = new ValidaSession().ObtenerUsuarioSession();
            ViewBag.TipoEmpresa = usuarioInfo.TipoEmpresa;
            return View();
        }

        public JsonResult GetSolicitudFacturaList(int? idSolicitudFactura, int? idEstatus, DateTime? fechaInicio, DateTime? fechaFin)
        {
            var usuarioInfo = new ValidaSession().ObtenerUsuarioSession();
            SolicitudFacturaBusiness businessLogic = new SolicitudFacturaBusiness();
            var request = new SolicitudFacturaRequestModel
            {
                SolicitudFacturaFiltro = new SolicitudFacturaFiltroModel
                {
                    IdProveedor = usuarioInfo.IdProveedor,
                    IdSolicitudFactura = idSolicitudFactura,
                    IdEstatus = idEstatus,
                    FechaInicio = fechaInicio,
                    FechaFin = fechaFin
                }
            };

            var solicitudFacturaResponse = businessLogic.GetSolicitudFacturaList(request);
          
            foreach(var solicitud in solicitudFacturaResponse.SolicitudFacturaList)
            {
                solicitud.Fecha = solicitud.FechaSolicitud.ToShortDateString();
                solicitud.RutaPDF = ConfigurationManager.AppSettings["urlApi"] + "api/SolicitudFactura/Documento?idSolicitudFactura=" + solicitud.IdSolicitudFactura;//"TRL891222ST7_4_d7e720c8-bdfd-4597-bbab-e9aa40d8413a.pdf";//documento.NombreArchivo;
                solicitud.RutaXML = usuarioInfo.TipoEmpresa == 1 ? ConfigurationManager.AppSettings["urlApi"] + "api/SolicitudFactura/Documento?idSolicitudFactura=" + solicitud.IdSolicitudFactura : "";//"SQP981128289_29_d7e720c8-bdfd-4597-bbab-e9aa40d8413a.xml";//documento.NombreArchivo;
            }
            
            return Json(solicitudFacturaResponse.SolicitudFacturaList, JsonRequestBehavior.AllowGet);           

        }

        public JsonResult GetSolicitudDetalleList(int idSolicitudFactura)
        {
            SolicitudFacturaBusiness businessLogic = new SolicitudFacturaBusiness();
            var request = new SolicitudFacturaDetalleRequestDTO
            {
                IdSolicitudFactura = idSolicitudFactura
            };

            var solicitudDetalleResponse = businessLogic.GetSolicitudFacturaDetalle(request);

            return Json(solicitudDetalleResponse, JsonRequestBehavior.AllowGet);

        }

        public ActionResult ExportToExcel(int idSolicitudFactura)
        {
            try
            {
                SolicitudFacturaBusiness businessLogic = new SolicitudFacturaBusiness();
                var request = new SolicitudFacturaDetalleRequestDTO
                {
                    IdSolicitudFactura = idSolicitudFactura
                };
                var solicitudDetalleResponse = businessLogic.GetSolicitudFacturaDetalle(request);
                if (solicitudDetalleResponse.Success)
                {
                    DataTable dataTable = new DataTable();
                    dataTable.Columns.Add("ID Lineas", typeof(int));
                    dataTable.Columns.Add("Descripción", typeof(string));
                    dataTable.Columns.Add("Cantidad Total", typeof(decimal));
                    dataTable.Columns.Add("Monto Total", typeof(decimal));
                    dataTable.Columns.Add("Cantidad Pendiente", typeof(decimal));
                    dataTable.Columns.Add("Monto Pendiente", typeof(decimal));
                    dataTable.Columns.Add("Cantidad Solicitada", typeof(decimal));
                    dataTable.Columns.Add("Monto Solicitado", typeof(decimal));

                    //dataTable.Columns.Add("ID Lineas", typeof(int));
                    //dataTable.Columns.Add("Descripción", typeof(string));
                    //dataTable.Columns.Add("Cantidad Adquirida", typeof(decimal));
                    //dataTable.Columns.Add("Precio Unitario", typeof(decimal));
                    //dataTable.Columns.Add("Importe Adquirido", typeof(decimal));
                    //dataTable.Columns.Add("Cantidad Facturada", typeof(decimal));
                    //dataTable.Columns.Add("Cantidad a Facturar", typeof(decimal));
                    //dataTable.Columns.Add("Importe Facturado sin I.V.A.", typeof(decimal));
                    //dataTable.Columns.Add("Importe a Facturar sin I.V.A.", typeof(decimal));

                    foreach (var solicitud in solicitudDetalleResponse.SolicitudFacturaDetalleList)
                    {
                        DataRow row = dataTable.NewRow();
                        row[0] = solicitud.Linea;
                        row[1] = solicitud.Descripcion;
                        row[2] = solicitud.CantidadTotal;
                        row[3] = solicitud.MontoTotal;
                        row[4] = solicitud.CantidadPendiente;
                        row[5] = solicitud.MontoPendiente;
                        row[6] = solicitud.CantidadSolicitada;
                        row[7] = solicitud.MontoSolicitada;

                        //row[0] = solicitud.Linea;
                        //row[1] = solicitud.Descripcion;
                        //row[2] = solicitud.CantidadAdquirida;
                        //row[3] = solicitud.PrecioUnitario;
                        //row[4] = solicitud.ImporteAdquirido;
                        //row[5] = solicitud.CantidadFacturada;
                        //row[6] = solicitud.CantidadFacturar;
                        //row[7] = solicitud.ImporteFacturado;
                        //row[8] = solicitud.ImporteFacturar;
                        dataTable.Rows.Add(row);
                    }

                    var memoryStream = new MemoryStream();
                    using (var excelPackage = new ExcelPackage(memoryStream))
                    {
                        var worksheet = excelPackage.Workbook.Worksheets.Add("Solicitud");
                        worksheet.Cells["A1"].LoadFromDataTable(dataTable, true, OfficeOpenXml.Table.TableStyles.None);
                        worksheet.Cells["A1:AN1"].Style.Font.Bold = true;
                        //worksheet.DefaultRowHeight = 18;

                        //worksheet.Column(2).Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Left;
                        //worksheet.Column(6).Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Center;
                        //worksheet.Column(7).Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Center;
                        worksheet.DefaultColWidth = 20;
                        worksheet.Column(2).AutoFit();

                        byte[] data = excelPackage.GetAsByteArray();
                        var date = DateTime.Now;
                        return File(data, "application/octet-stream", "SolicitudDetalle_" + date.ToShortDateString() + ".xlsx");
                    }
                }
                else
                {
                    return new EmptyResult();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public JsonResult GetFacturaList(
            string IdAeropuerto,

EPROCURENTWEB/Controllers/SeguridadController.cs
using EPROCUREMENT.GAPPROVEEDOR.Entities;
using EprocurementWeb.Business;
using EprocurementWeb.Filters;
using EprocurementWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EprocurementWeb.Controllers
{
    public class SeguridadController : Controller
    {
        // GET: Seguridad
        public ActionResult Index()
        {
            UsuarioModel usuario = new UsuarioModel();
            Session["User"] = null;
            ViewBag.Error = "";
            return View(usuario);
        }

        [HttpPost]
        public ActionResult Login(UsuarioModel usuario)
        {
            try
            {
                UsuarioDTO usuarioDTO = new BusinessLogic().LoginUsuarioItem(usuario.NombreUsuario, usuario.Password);
                if (usuarioDTO == null)
                {
                    ViewBag.Error = "Usuario o contraseña invalida";
                    return View("Index");
                }
                if (usuarioDTO.IdEstatus == 3 ||  usuarioDTO.IdEstatus == 4 || usuarioDTO.IdEstatus == 5 || usuarioDTO.IdEstatus == 7)
                {
                    Session["User"] = usuarioDTO;
                    return RedirectToAction("InformacionBF", "AltaProveedor");
                }
                if (usuarioDTO.IdEstatus == 8 || usuarioDTO.IdEstatus == 9 || usuarioDTO.IdEstatus == 10)
                {
                    Session["User"] = usuarioDTO;
                    return RedirectToAction("Index", "Gestion");
                }

                else if (usuarioDTO.IdEstatus == 1 || usuarioDTO.IdEstatus == 2 || usuarioDTO.IdEstatus == 3 || usuarioDTO.IdEstatus == 6)
                {
                    ViewBag.Error = "El usuario no está activo o fue rechazado";
                    return View("Index");
                }

                ViewBag.Error = "Usuario o contraseña invalida";
                return View("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Se generó un problema al procesar el acceso";
                return View("Index");
                //return View();
            }

        }

        [HttpGet]
        public ActionResult IniciarRecuperacion()
        {
            UsuarioModel usuario = new UsuarioModel();
            
            return View(usuario);
        }

        [HttpPost]
        public ActionResult IniciarRecuperacion(UsuarioModel usuario)
        {
            if (string.IsNullOrWhiteSpace(usuario.NombreUsuario))
            {
                ViewBag.Error = "Debe ingresar el RFC.";
                return View("Index");
            }
            string token = new BusinessLogic().RecuperarPasswordUsuario(usuario.NombreUsuario, true);
            if (!string.IsNullOrEmpty(token))
            {
                return Redirect("/Seguridad/IniciarRecuperacion#success");
                //ViewBag.Error = "Hemos enviado un email a su correo para continuar con el proceso.";
            }
            else
            {
                return Redirect("/Seguridad/IniciarRecuperacion#errorSuccess");
                //ViewBag.Error = "Ocurrió un error al intentar iniciar el proceso";
            }
            return View();
        }

        [HttpGet]
        public ActionResult Recovery(string token)
        {
            //var usuarioInfo = new ValidaSession().ObtenerUsuarioSession();
            //if (usuarioInfo != null)
            //{
            //usuarioInfo.Token = new BusinessLogic().RecuperarPasswordUsuario(usuarioInfo, true);
            //if (usuarioInfo.Token != null)
            //{
            var usuarioModel = new UsuarioModel
            {
                Token = token
            };
            //    return View(usuarioModel);
            //}
            //else
            //{
            //    ViewBag.Error = "Error al generar la solicitud";
            //    return View("Index");
            //}

            //ViewBag.Error = "Error al generar la solicitud";
            return View(usuarioModel);
            //}

            //ViewBag.Error = "Tu token ha expirado";
            //return View("Index");
        }

        [HttpPost]
        public ActionResult Recovery(UsuarioModel usuario)
        {
            ViewBag.Error = "";
            if (usuario != null && usuario.PasswordNueva != null && usuario.ConfirmarPassword != null)
            {
                //var usuarioInfo = new ValidaSession().ObtenerUsuarioSession();
                //if (usuarioInfo != null)
                //{
                //usuarioInfo.Token = usuario.Token;
                if (!new BusinessLogic().RecuperarPasswordUsuario(usuario, false))
                {
                    return Redirect("/Seguridad/Recovery#errorSuccess");
                    ViewBag.Error = "Error al generar la solicitud";
                } else
                {
                    return Redirect("/Seguridad/Recovery#success");
                    ViewBag.Error = "Sin error";
                }
                //}
            } else
            {
                ViewBag.Error = "Las contraseñas deben ser igules";
            }

            return View();
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult GetInoformacionUsuario()
        {
            UsuarioDTO usuario = null;
            usuario = new ValidaSession().ObtenerUsuarioSession();
            return Json(usuario, JsonRequestBehavior.AllowGet);
        }
    }
}

EPROCURENTWEB/Views/Shared/_ActualizarPassword.cshtml
@model EprocurementWeb.Models.ActualizaPasswordModel
@using (Html.BeginForm("ActualizarPassword", "MiCuenta", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="col100" style="font-size:14px;">

        @Html.ValidationSummary(true)
        <div class="col100 mt-2">
            <div class="col25">
                <div class="inputIF">
                    @Html.LabelFor(model => model.Password, new { @class = "labelTexto control-label" })
                </div>
                <div class="inputIF">
                    @Html.PasswordFor(model => model.Password, new { @class = "form-control inputIF" })
                </div>
            </div>
            <div class="col25">
                <div class="inputIF">
                    @Html.LabelFor(model => model.PasswordNueva, new { @class = "labelTexto control-label" })
                </div>
                <div class="inputIF">
                    @Html.PasswordFor(model => model.PasswordNueva, new { @class = "form-control inputIF" })
                </div>
            </div>
            <div class="col25">
                <div class="inputIF">
                    @Html.LabelFor(model => model.ConfirmarPassword, new { @class = "labelTexto control-label" })
                </div>
                <div class="inputIF">
                    @Html.PasswordFor(model => model.ConfirmarPassword, new { @class = "form-control inputIF" })
                </div>
            </div>
        </div>
        <div class="col100 mt-2">
            <div class="col25">
                <div class="inputIF">
                    @Html.ValidationMessageFor(model => model.Password)
                </div>
            </div>
            <div class="col25">
                <div class="inputIF">
                    @Html.ValidationMessageFor(model => model.PasswordNueva)
                </div>
            </div>
            <div class="col25">
                <div class="inputIF">
                    @Html.ValidationMessageFor(model => model.ConfirmarPassword)
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-sm-8">&nbsp;</div>
        <div class="col-sm-2"><input type="button" value="Cancelar" class="btnStyle btnWhite" /></div>
        <div class="col-sm-2"><input type="submit" value="Aceptar" class="btnStyle" /></div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        if (window.location.hash == "#psuccess") {
            Swal.fire({
                position: 'middle',
                icon: 'success',
                title: '¡Actualización de Contraseña Exitosa!',
                html: '',
                showConfirmButton: true,
                timer: 3000
            })
        }
        });
</script>

EPROCURENTWEB/Views/Shared/_Contact.cshtml
@model EprocurementWeb.Models.ContactModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@RHome.Contact</h4>
        <hr />

        @if (ViewBag.ContactResult != null)
        {
            var classFromResult = ViewBag.ContactResult ? "text-success" : "text-danger";
            <p class="@classFromResult"><strong>@ViewBag.ContactResultMessage</strong></p> 
        }
        else 
        { 
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ContactName, 
                    htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ContactName, 
                        new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ContactName, "", 
                        new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContactEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ContactEmail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ContactEmail, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="@RGlobal.Send" class="btn btn-default" />
                </div>
            </div>
        }
    </div>
}


@Scripts.Render("~/bundles/jqueryval")
@if (GlobalHelper.DefaultCulture != GlobalHelper.CurrentCulture)
{
    <script src="@Url.GetScript("jquery.validate.extension.js")" defer></script>
}

EPROCURENTWEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @*@Styles.Render("~/Content/css")*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/Styles/Site.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.css" />
    <link href="~/Content/Gestor.css" rel="stylesheet" />
    <style>
        .input-grid {
            border: none !important;
        }

        table.dataTable thead th, table.dataTable thead td {
            border-bottom: none !important;
        }

        table.dataTable.no-footer {
            border-bottom: none !important;
        }

        #Table_info {
            display: none;
        }
    </style>
</head>
<body>
    <div class="" style="width:100%; background-color:white;">
        <div class="row panel-header" style="width:100%;">
            <div class="col-sm-4">
                <img class="gap-logo" src="~/Content/Images/logo-gap-color.png" />
            </div>

            <div class="col-sm-4 t-a-c">
                <h1 class="h-title">
                    Bienvenido al portal de proveedor
                </h1>
            </div>

            <div class="" style="flex: 0 0 33.333333%; max-width: 33.333333%;">
                <table width="100%" class="panel-user-control">
                    <tr>
                        <td>
                            <div class="menu-user">
                                <span style="font-weight:600; font-size:12px;" id="userInfo"></span> <img class="padding-user" src="~/Content/Images/user-photo.png" width="25" />
                                <ul>
                                    <li><a href="@Url.Action("Index", "MiCuenta")">Mi cuenta</a></li>
                                    <li><a href="@Url.Action("Index", "Contacto")">Contactos</a></li>
                                    <li><a href="@Url.Action("ActualizarPassword", "MiCuenta")">Cambiar Contraseña</a></li>
                                    <li><a href="@Url.Action("Index", "Seguridad")">Cerrar sesión</a></li>
                                </ul>
                            </div>
                        </td>
                        <td width="32px" style="border:none; border-left:solid 1px #f9f9f9;">
                            <a href="@Url.Action("Index", "Seguridad")">
                                <img class="padding-user cursor" src="~/Content/Images/shutdow-icon.png" width="25" />
                            </a>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <div class="row-nav" style="width:100%;">
        <div class="container">
            <nav class="navbar navbar-expand-lg">
                @*<a class="navbar-brand" href="#">Navbar</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li id="nav-1" class="nav-item">
                            @*@Html.ActionLink("Facturas", "InformacionBF", "AltaProveedor", new { @class = "nav-link" })*@
                            @*<a class="nav-link" href="Index">Facturas <span class="sr-only"></span></a>*@
                            <a class="nav-link" href="@Url.Action("Index", "Gestion")">Facturas</a>
                        </li>
                        @*@if (ViewBag.view == 2) { active }*@
                        <li id="nav-2" class="nav-item">
                            @*<a class="nav-link" href="SolicitudFacturacion">Solicitud de facturación <span class="sr-only"></span></a>*@
                            <a class="nav-link" href="@Url.Action("SolicitudFacturacion", "Gestion")">Solicitud de facturación</a>
                        </li>
                        <li id="nav-3" class="nav-item">
                            @*<a class="nav-link" href="SolicitudCotizacion">Solicitud de cotización <span class="sr-only"></span></a>*@
                            <a class="nav-link" href="@Url.Action("SolicitudCotizacion", "Gestion")">Solicitud de cotización</a>
                        </li>
                        <li id="nav-4" class="nav-item">
                            @*<a class="nav-link" href="OrdenCompra">Órden de compra<span class="sr-only"></span></a>*@
                            <a class="nav-link" href="@Url.Action("OrdenCompra", "Gestion")">Órden de compra</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="container">
            @RenderBody()
        </div>

        <hr />
        <footer>
        </footer>
    </div>

    @Scripts.Render("~/bundles/datatable")
    @*<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.js"></script>*@
    @Scripts.Render("~/bundles/bootstrap")
    @*<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

<script type="text/javascript">
    $(document).ready(function () {
        $.getJSON("/Seguridad/GetInoformacionUsuario",
            function (data) {
                if (data != null && data.NombreUsuario != null)
                    $("#userInfo").html(data.NombreUsuario);
            });
    });
</script>

EPROCURENTWEB/Views/Shared/_LayoutInit.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/shared")

</head>
<body>
    @*
        <nav class="navbar navbar-expand-lg navbar-dark bg-test">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="langs" style="list-style:none;">
                    <li style="display:inline;">
                        <a href="" class="setLang" data-lang="es-MX"><img src="@Url.GetImage("Mexico.png",false)" /></a>
                    </li>
                    <li style="display:inline;">
                        <a href="" class="setLang" data-lang="en-US"><img src="@Url.GetImage("usa.png", false)" /></a>
                    </li>
                </ul>
            </div>
        </nav>*@



    <div class="general">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>


    @RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {

            var lang = EprocurementWeb.Cookies.getCookie("LangForMultiLanguage");
            $(".setLang[data-lang='" + lang + "'] img").addClass("active-lang");

            $(".setLang").on("click", function (event) {
                var lang = $(this).attr("data-lang");
                EprocurementWeb.Cookies.setCookie("LangForMultiLanguage", lang, 30);
                location.reload(true);
            })
        });
        $(document).on('click', '.panel-heading span.clickable', function (e) {
            var $this = $(this);
            if (!$this.hasClass('panel-collapsed')) {
                $this.parents('.panel').find('.panel-body').slideUp();
                $this.addClass('panel-collapsed');
                $this.find('i').removeClass('glyphicon-chevron-up').addClass('glyphicon-chevron-down');
            } else {
                $this.parents('.panel').find('.panel-body').slideDown();
                $this.removeClass('panel-collapsed');
                $this.find('i').removeClass('glyphicon-chevron-down').addClass('glyphicon-chevron-up');
            }
        })
    </script>

</body>
</html>