EPROCURENTWEB/Models/OrdenCompra/OrdenCompraDetalleFiltroModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EprocurementWeb.Models
{
    public class OrdenCompraDetalleFiltroModel
    {
        public string OrdenCompra { get; set; }
    }
}

EPROCURENTWEB/Models/OrdenCompra/OrdenCompraDetalleModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EprocurementWeb.Models
{
    public class OrdenCompraDetalleModel
    {
        public int Linea { get; set; }
        public string OrdenCompra { get; set; }
        public string Empresa { get; set; }
        public string Agrupador { get; set; }
        public string CentroCosto { get; set; }
        public string TipoPresupuesto { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Recibido { get; set; }
        public decimal Facturado { get; set; }
        public string Solicitud { get; set; }
        public decimal Precio { get; set; }
        public decimal Monto { get; set; }
        public string Categoria { get; set; }
        public string Producto { get; set; }
        public string Unidad { get; set; }
        public string Moneda { get; set; }
        public string ImpuestosxVenta { get; set; }
        public string CuentaProveedor { get; set; }
        public string RECIDLinSol { get; set; }
        public int EsConvenio { get; set; }
    }
}

EPROCURENTWEB/Models/OrdenCompra/OrdenCompraFiltroModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EprocurementWeb.Models
{
    public class OrdenCompraFiltroModel
    {
        public int? IdProveedor { get; set; }
        public string OrdenCompra { get; set; }
        public int? IdEstatus { get; set; }
    }
}

EPROCURENTWEB/Models/OrdenCompra/OrdenCompraModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EprocurementWeb.Models
{
    public class OrdenCompraModel
    {
        public string NumeroProveedor { get; set; }
        public string Moneda { get; set; }
        public string Empresa { get; set; }
        public string OrdenCompra { get; set; }
        public string Descripcion { get; set; }
        public decimal Importe { get; set; }
        public int IdEstatus { get; set; }
        public string Estatus { get; set; }
    }
}

EPROCURENTWEB/Controllers/GestionController.cs
using EprocurementWeb.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EprocurementWeb.Models;
using EprocurementWeb.Filters;
using EPROCUREMENT.GAPPROVEEDOR.Entities;
using System.IO;
using System.Text;
using System.Web.UI.WebControls;
using System.Web.UI;
using OfficeOpenXml;
using System.Data;
using DocumentFormat.OpenXml.Spreadsheet;
using System.Xml.Schema;
using System.Configuration;
using System.Net.Http;
using System.Xml;
using System.Xml.Serialization;
using System.Xml.Linq;
using EprocurementWeb.SatServiceReference;

namespace EprocurementWeb.Controllers
{
    public class GestionController : Controller
    {
        public List<AeropuertoListaDTO> AeropuertoList;
        public string nav_factura;
        public string nav_sFactura;
        public string nav_sCotizacion;
        public string nav_sOC;
        // GET: Gestion
        public ActionResult Index()
        {
            GetAeropuertoList();
            ViewBag.AeropuertoList = AeropuertoList;
            
            //var aa = GetFacturaList(null, null, null, null, null, null, null);
            return View();
        }


        // GET: SolicitudFacturacion
        public ActionResult SolicitudFacturacion()
        {
            var usuarioInfo = new ValidaSession().ObtenerUsuarioSession();
            ViewBag.TipoEmpresa = usuarioInfo.TipoEmpresa;
            List<EstatusSolicitudModel> estatusList = new List<EstatusSolicitudModel>();
            estatusList.Add(new EstatusSolicitudModel { IdEstatus = 1, Descripcion = "Pendiente" });
            estatusList.Add(new EstatusSolicitudModel { IdEstatus = 2, Descripcion = "En Proceso" });
            estatusList.Add(new EstatusSolicitudModel { IdEstatus = 3, Descripcion = "Aceptada" });
            estatusList.Add(new EstatusSolicitudModel { IdEstatus = 4, Descripcion = "Cancelada por AX" });
            estatusList.Add(new EstatusSolicitudModel { IdEstatus = 5, Descripcion = "Pagada" });
            ViewBag.EstatusSolicitudList = estatusList;

            List<SolicitudFactura> numeroSolicitudList = new List<SolicitudFactura>();
            numeroSolicitudList.Add(new SolicitudFactura { IdSolicitudFactura = 4 });
            numeroSolicitudList.Add(new SolicitudFactura { IdSolicitudFactura = 5 });
            numeroSolicitudList.Add(new SolicitudFactura { IdSolicitudFactura = 6 });
            numeroSolicitudList.Add(new SolicitudFactura { IdSolicitudFactura = 7 });
            ViewBag.NumeroSolicitudList = numeroSolicitudList;


            return View();
        }

        // GET: SolicitudFacturacion
        public ActionResult SolicitudDetalle(int idSolicitudFactura)
        {
            ViewBag.IdSolicitudFactura = idSolicitudFactura;
            var usuarioInfo = new ValidaSession().ObtenerUsuarioSession();
            ViewBag.TipoEmpresa = usuarioInfo.TipoEmpresa;
            return View();
        }

        public JsonResult GetSolicitudFacturaList(int? idSolicitudFactura, int? idEstatus, DateTime? fechaInicio, DateTime? fechaFin)
        {
            var usuarioInfo = new ValidaSession().ObtenerUsuarioSession();
            SolicitudFacturaBusiness businessLogic = new SolicitudFacturaBusiness();
            var request = new SolicitudFacturaRequestModel
            {
                SolicitudFacturaFiltro = new SolicitudFacturaFiltroModel
                {
                    IdProveedor = usuarioInfo.IdProveedor,
                    IdSolicitudFactura = idSolicitudFactura,
                    IdEstatus = idEstatus,
                    FechaInicio = fechaInicio,
                    FechaFin = fechaFin
                }
            };

            var solicitudFacturaResponse = businessLogic.GetSolicitudFacturaList(request);
          
            foreach(var solicitud in solicitudFacturaResponse.SolicitudFacturaList)
            {
                solicitud.Fecha = solicitud.FechaSolicitud.ToShortDateString();
                solicitud.RutaPDF = ConfigurationManager.AppSettings["urlApi"] + "api/SolicitudFactura/Documento?idSolicitudFactura=" + solicitud.IdSolicitudFactura;//"TRL891222ST7_4_d7e720c8-bdfd-4597-bbab-e9aa40d8413a.pdf";//documento.NombreArchivo;
                solicitud.RutaXML = usuarioInfo.TipoEmpresa == 1 ? ConfigurationManager.AppSettings["urlApi"] + "api/SolicitudFactura/Documento?idSolicitudFactura=" + solicitud.IdSolicitudFactura : "";//"SQP981128289_29_d7e720c8-bdfd-4597-bbab-e9aa40d8413a.xml";//documento.NombreArchivo;
            }
            
            return Json(solicitudFacturaResponse.SolicitudFacturaList, JsonRequestBehavior.AllowGet);           

        }

        public JsonResult GetSolicitudDetalleList(int idSolicitudFactura)
        {
            SolicitudFacturaBusiness businessLogic = new SolicitudFacturaBusiness();
            var request = new SolicitudFacturaDetalleRequestDTO
            {
                IdSolicitudFactura = idSolicitudFactura
            };

            var solicitudDetalleResponse = businessLogic.GetSolicitudFacturaDetalle(request);

            return Json(solicitudDetalleResponse, JsonRequestBehavior.AllowGet);

        }

        public ActionResult ExportToExcel(int idSolicitudFactura)
        {
            try
            {
                SolicitudFacturaBusiness businessLogic = new SolicitudFacturaBusiness();
                var request = new SolicitudFacturaDetalleRequestDTO
                {
                    IdSolicitudFactura = idSolicitudFactura
                };
                var solicitudDetalleResponse = businessLogic.GetSolicitudFacturaDetalle(request);
                if (solicitudDetalleResponse.Success)
                {
                    DataTable dataTable = new DataTable();
                    dataTable.Columns.Add("ID Lineas", typeof(int));
                    dataTable.Columns.Add("Descripción", typeof(string));
                    dataTable.Columns.Add("Cantidad Total", typeof(decimal));
                    dataTable.Columns.Add("Monto Total", typeof(decimal));
                    dataTable.Columns.Add("Cantidad Pendiente", typeof(decimal));
                    dataTable.Columns.Add("Monto Pendiente", typeof(decimal));
                    dataTable.Columns.Add("Cantidad Solicitada", typeof(decimal));
                    dataTable.Columns.Add("Monto Solicitado", typeof(decimal));

                    //dataTable.Columns.Add("ID Lineas", typeof(int));
                    //dataTable.Columns.Add("Descripción", typeof(string));
                    //dataTable.Columns.Add("Cantidad Adquirida", typeof(decimal));
                    //dataTable.Columns.Add("Precio Unitario", typeof(decimal));
                    //dataTable.Columns.Add("Importe Adquirido", typeof(decimal));
                    //dataTable.Columns.Add("Cantidad Facturada", typeof(decimal));
                    //dataTable.Columns.Add("Cantidad a Facturar", typeof(decimal));
                    //dataTable.Columns.Add("Importe Facturado sin I.V.A.", typeof(decimal));
                    //dataTable.Columns.Add("Importe a Facturar sin I.V.A.", typeof(decimal));

                    foreach (var solicitud in solicitudDetalleResponse.SolicitudFacturaDetalleList)
                    {
                        DataRow row = dataTable.NewRow();
                        row[0] = solicitud.Linea;
                        row[1] = solicitud.Descripcion;
                        row[2] = solicitud.CantidadTotal;
                        row[3] = solicitud.MontoTotal;
                        row[4] = solicitud.CantidadPendiente;
                        row[5] = solicitud.MontoPendiente;
                        row[6] = solicitud.CantidadSolicitada;
                        row[7] = solicitud.MontoSolicitada;

                        //row[0] = solicitud.Linea;
                        //row[1] = solicitud.Descripcion;
                        //row[2] = solicitud.CantidadAdquirida;
                        //row[3] = solicitud.PrecioUnitario;
                        //row[4] = solicitud.ImporteAdquirido;
                        //row[5] = solicitud.CantidadFacturada;
                        //row[6] = solicitud.CantidadFacturar;
                        //row[7] = solicitud.ImporteFacturado;
                        //row[8] = solicitud.ImporteFacturar;
                        dataTable.Rows.Add(row);
                    }

                    var memoryStream = new MemoryStream();
                    using (var excelPackage = new ExcelPackage(memoryStream))
                    {
                        var worksheet = excelPackage.Workbook.Worksheets.Add("Solicitud");
                        worksheet.Cells["A1"].LoadFromDataTable(dataTable, true, OfficeOpenXml.Table.TableStyles.None);
                        worksheet.Cells["A1:AN1"].Style.Font.Bold = true;
                        //worksheet.DefaultRowHeight = 18;

                        //worksheet.Column(2).Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Left;
                        //worksheet.Column(6).Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Center;
                        //worksheet.Column(7).Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Center;
                        worksheet.DefaultColWidth = 20;
                        worksheet.Column(2).AutoFit();

                        byte[] data = excelPackage.GetAsByteArray();
                        var date = DateTime.Now;
                        return File(data, "application/octet-stream", "SolicitudDetalle_" + date.ToShortDateString() + ".xlsx");
                    }
                }
                else
                {
                    return new EmptyResult();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public JsonResult GetFacturaList(
            string IdAeropuerto,

EPROCURENTWEB/Views/Gestion/DetalleFactura.cshtml
@{
    ViewBag.Title = "Detalle Facturas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/Styles/Site.css" rel="stylesheet" />
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/Css/infoCuenta.css" rel="stylesheet" />
<link href="~/Content/validacionProveedor.css" rel="stylesheet" />

<div class="row">
    <div class="col-md-12">
        <h5 class="mt-2 detalle-titulo">Detalle de la factura</h5>
        <div class="card mt-3">
            <div class="card-header mb-2" id="headingOne">
                <span class="card-titulo">
                    Orden: @Html.Label("lblOrdenCompra", "...", new { id = "lblOrdenCompra" })
                </span>
            </div>
            @Html.Hidden("idFactura", (int)ViewBag.idFactura)
            <div class="card-body no-border">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="row ml-2">
                            <div class="col-sm-5"><p class="control-label">Recepción de producto</p></div>
                            <div class="col-sm-7">@Html.Label("lblRecepcion", "...", new { id = "lblRecepcion" })</div>
                            @*@Html.Label("lblDescripcion", "...", new { id = "lblDescripcion" })*@
                        </div>
                        <div class="row ml-2">
                            <div class="col-sm-5"><p class="control-label">Fecha recepción</p></div>
                            <div class="col-sm-7">@Html.Label("lblFechaRecepcion", "...", new { id = "lblFechaRecepcion" })</div>
                        </div>
                        <div class="row ml-2">
                            <div class="col-sm-5"><p class="control-label">Subtotal</p></div>
                            <div class="col-sm-7">$ @Html.Label("lblSubtotal", "...", new { id = "lblSubtotal" })</div>
                        </div>
                        <div class="row ml-2">
                            <div class="col-sm-5"><p class="control-label">Anticipo</p></div>
                            <div class="col-sm-7">$ @Html.Label("lblAnticipo", "...", new { id = "lblAnticipo" })</div>
                        </div>
                        <div class="row ml-2">
                            <div class="col-sm-5"><p class="control-label">Impuestos</p></div>
                            <div class="col-sm-7">$ @Html.Label("lblImpuestos", "...", new { id = "lblImpuestos" })</div>
                        </div>
                        <div class="row ml-2">
                            <div class="col-sm-5"><p class="control-label">Total</p></div>
                            <div class="col-sm-7">$ @Html.Label("lblTotal", "...", new { id = "lblTotal" })</div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="row ml-2">
                            <div class="col-sm-5"><p class="control-label">Pagado</p></div>
                            <div class="col-sm-7">@Html.Label("lblPagado", "...", new { id = "lblPagado" })</div>
                        </div>
                        <div class="row ml-2">
                            <div class="col-sm-5"><p class="control-label">Facturado</p></div>
                            <div class="col-sm-7">@Html.Label("lblFacturado", "...", new { id = "lblFacturado" })</div>
                        </div>
                        <div class="row ml-2">
                            <div class="col-sm-5"><p class="control-label">Fecha de factura</p></div>
                            <div class="col-sm-7">@Html.Label("lblFechaFactura", "...", new { id = "lblFechaFactura" })</div>
                        </div>
                        <div class="row ml-2">
                            <div class="col-sm-5"><p class="control-label">No. de factura</p></div>
                            <div class="col-sm-7">@Html.Label("lblNoFactura", "...", new { id = "lblNoFactura" })</div>
                        </div>
                        <div class="row ml-2">
                            <div class="col-sm-5"><p class="control-label">Fecha programada de pago</p></div>
                            <div class="col-sm-7">@Html.Label("lblFechaPago", "...", new { id = "lblFechaPago" })</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var fn_buscar = function () {
        var idFactura = $('#idFactura').val() == '' ? null : $('#idFactura').val();
        var jsonData = JSON.stringify({ idFactura: idFactura });
            $.ajax({
                type: "POST",
                contentType: "application/json; charset=utf-8",
                url: '@Url.Action("GetFacturaDetalle", "Gestion")',
                data: jsonData,
                async: false,
                success: function (data) {
                    $("#lblOrdenCompra").html(data.FacturaDetalleDTO.OrdenCompra);
                    $("#lblRecepcion").html(data.FacturaDetalleDTO.NoFactura);
                    $("#lblFechaRecepcion").html(data.FacturaDetalleDTO.FechaRecepcion);
                    $("#lblSubtotal").html(addCommas(data.FacturaDetalleDTO.Subtotal));
                    $("#lblAnticipo").html(addCommas(data.FacturaDetalleDTO.Anticipo));
                    $("#lblImpuestos").html(addCommas(data.FacturaDetalleDTO.Impuestos));
                    $("#lblTotal").html(addCommas(data.FacturaDetalleDTO.Total));
                    $("#lblPagado").html(data.FacturaDetalleDTO.Pagado);
                    $("#lblFacturado").html(data.FacturaDetalleDTO.Facturado);
                    $("#lblFechaFactura").html(data.FacturaDetalleDTO.FechaFactura);
                    $("#lblNoFactura").html(data.FacturaDetalleDTO.NoFactura);
                    $("#lblFechaPago").html(data.FacturaDetalleDTO.FechaPago);
                    console.log("GetFacturaDetalle", data );
                },
            });
        }
    function addCommas(nStr) {
        nStr += '';
        x = nStr.split('.');
        x1 = x[0];
        x2 = x.length > 1 ? '.' + x[1] : '';
        var rgx = /(\d+)(\d{3})/;
        while (rgx.test(x1)) {
            x1 = x1.replace(rgx, '$1' + ',' + '$2');
        }
        return x1 + x2;
    }

    $(".navbar-nav .nav-item").removeClass("active");
    $("#nav-1").addClass("active");

    $(document).ready(function () {
        fn_buscar();
    });

</script>

EPROCURENTWEB/Views/Gestion/Index.cshtml
@{
    ViewBag.Title = "Facturas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<!-- Bootstrap DatePicker -->
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
<script src="~/scripts\jquery-ui-1.12.1.min.js"></script>
<!-- Bootstrap DatePicker -->

<div class="row">
    <div class="col-md-12">
        <div class="card mt-3">
            <div class="card-body">
                <div class="row" style="">
                    <div class="col-md-12 h-filtro">Filtrar por</div>
                    <div class="form-group col-md-4">
                        <label class="control-label text-right">Aeropuerto</label>
                        @Html.DropDownList("idAeropuerto", new SelectList(ViewBag.AeropuertoList, "Id", "Nombre"), "Seleccionar", new { @class = "form-control" })
                        @*<select class="form-control" id="idAeropuerto">
                                <option>Selecione</option>
                            </select>*@
                    </div>
                    <div class="form-group col-md-4">
                        <label class="control-label text-right">Orden de compra</label>
                        <input type="text" class="form-control" id="OrdenCompra" />
                    </div>
                    <div class="form-group col-md-4">
                        <label class="control-label text-right">Folio</label>
                        <input type="text" class="form-control" id="Folio" />
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-4">
                        <div class="row">
                            <div class="col-sm-12"><label class="control-label text-right">Fecha de factura</label></div>
                            <div class="col-sm-2"> <label class="control-label text-right" style="color:#68686a !important">Inicio</label> </div>
                            <div class="col-sm-4">
                                <input type="text" autocomplete="off" name="FechaFacInicio" style="font-size:12px;" class="form-control datepicker" id="FechaFacInicio" size="15" onkeydown="return false" placeholder="" data-date-format="dd/mm/yyyy">
                            </div>
                            <div class="col-sm-2"> <label class="control-label text-right" style="color:#68686a !important">Fin</label> </div>
                            <div class="col-sm-4">
                                <input type="text" autocomplete="off" name="FechaFacFin" style="font-size:12px;" class="form-control datepicker" id="FechaFacFin" size="15" onkeydown="return false" placeholder="" data-date-format="dd/mm/yyyy">
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <div class="row">
                            <div class="col-sm-12"><label class="control-label text-right">Fecha propuesta de pago</label></div>
                            <div class="col-sm-2"> <label class="control-label text-right" style="color:#68686a !important">Inicio</label> </div>
                            <div class="col-sm-4">
                                <input type="text" autocomplete="off" name="FechaPagoInicio" style="font-size:12px;" class="form-control datepicker" id="FechaPagoInicio" size="15" onkeydown="return false" placeholder="" data-date-format="dd/mm/yyyy">
                            </div>
                            <div class="col-sm-2"> <label class="control-label text-right" style="color:#68686a !important">Fin</label> </div>
                            <div class="col-sm-4">
                                <input type="text" autocomplete="off" name="FechaPagoFin" style="font-size:12px;" class="form-control datepicker" id="FechaPagoFin" size="15" onkeydown="return false" placeholder="" data-date-format="dd/mm/yyyy">
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <button id="buscar" class="btn btn-search btn-purple float-right" onclick="fn_buscar()">
                            <i class="fas fa-search"></i> Buscar
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row mt-3">
    <div class="col-sm-12">
        <table id="Table" class="dataTable dataTables_wrapper "></table>
    </div>
</div>

<script type="text/javascript">
    $.datepicker.regional['es'] = {
        closeText: 'Cerrar',
        prevText: '< Ant',
        nextText: 'Sig >',
        currentText: 'Hoy',
        monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
        monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
        dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
        dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Juv', 'Vie', 'Sáb'],
        dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sá'],
        weekHeader: 'Sm',
        dateFormat: 'dd/mm/yy',
        firstDay: 1,
        isRTL: false,
        showMonthAfterYear: false,
        yearSuffix: ''
    };
    $.datepicker.setDefaults($.datepicker.regional['es']);
    $(function () {
        $(".datepicker").datepicker({
            dateFormat: "dd/mm/yy",
            changeMonth: true,
            changeYear: true,
            //yearRange : "-10:+10"
            minDate: new Date(2018, 0, 1),
            maxDate: new Date(2019, 12, 1),
            showOn: "both",
            language: "es",
            showButtonPanel: false,
            buttonText: "<i class='fa fa-calendar'></i>"
        });
    });

    var fn_buscar = function () {

        var jsonData = JSON.stringify({
            idAeropuerto: $('#idAeropuerto').val() == '' ? null : $('#idAeropuerto').val(),
            OrdenCompra: $('#OrdenCompra').val() == '' ? null : $('#OrdenCompra').val(),
            Folio: $('#Folio').val() == '' ? null : $('#Folio').val(),
            FechaFacInicio: $('#FechaFacInicio').val() == '' ? null : $('#FechaFacInicio').val(),
            FechaFacFin: $('#FechaFacFin').val() == '' ? null : $('#FechaFacFin').val(),
            FechaPagoInicio: $('#FechaPagoInicio').val() == '' ? null : $('#FechaPagoInicio').val(),
            FechaPagoFin: $('#FechaPagoFin').val() == '' ? null : $('#FechaPagoFin').val()
        });

        console.log("#idAeropuerto", $('#idAeropuerto').val() );
        console.log("jsonData",jsonData );
         $.ajax({
             type: "POST",
             contentType: "application/json; charset=utf-8",
             url: '@Url.Action("GetFacturaList", "Gestion")',
             data: jsonData,
             async: false,
             success: function (data) {

                 $("#Table").html('');
                 $("#Table").append(
                     '<thead class="bg-light-purple"><tr>' +
                     '<td align="left">Aeropuerto</td>'+
                     '<td align="left">Número de orden de compra</td>' +
                     '<td align="left">Folio</td>' +
                     '<td align="right">Monto</td>' +
                     '<td align="center">Fecha de factura</td>' +
                     '<td align="center">Estatus</td>' +
                     '<td align="center">Fecha propuesta de pago</td>' +
                     '<td>Ver</td>'+
                     '</tr ></thead > '
                 );
                 $("#Table").DataTable().clear().draw();
                 $("#Table").DataTable().destroy();

                 $("#Table").append('<tbody>');
                 for (i = 0; i < data.length; i++) {

                     var link = '@Html.ActionLink(" ", "DetalleFactura", "Gestion", new { IdFactura = "_idFactura_" }, new { @class = "btn-ver" })';
                     link = link.replace('_idFactura_', data[i].IdFactura);

                     var color = ''
                     switch (data[i].IdEstatus) {
                         case 1: color = '#f9a32f'; // Pendiente
                             break;
                         case 2: color = '#448aff'; // En Proceso
                             break;
                         case 3: color = '#43ac3e'; // Aceptada
                             break;
                         case 4: color = '#de343c'; // Rechazada
                             break;
                         case 5: color = '#43ac3e'; // Aceptada
                             break;
                     }

                     $("#Table").append('<tr>' +
                         '<td style="dislay: none; text-transform:uppercase;" align="center"><b>' + data[i].Aeropuerto + '</b></td>' +
                         '<td style="dislay: none;" align="center">' + data[i].OrdenCompra + '</td>' +
                         '<td style="dislay: none;" align="center">' + data[i].Folio + '</td>' +
                         '<td style="dislay: none;" align="right">$ ' + addCommas(data[i].Monto) + '</td>' +
                         '<td style="dislay: none;" align="center">' + data[i].FechaFactura + '</td>' +
                         '<td style="dislay: none; color:' + color + '" align="center"><b>' + data[i].Estatus + '</b></td>' +
                         '<td style="dislay: none;" align="center">' + data[i].FechaPago + '</td>' +
                         '<td style="dislay: none;" align="center">'+ link +'</td>' + '</tr>'
                     );
                 }
                 $("#Table").append('</tbody>');

                 $('#Table').DataTable({
                        "paging": false,
                         "bScrollInfinite": true,
                         "bScrollCollapse": true
                     });
             }
         });
    }

    function addCommas(nStr)
    {
        nStr += '';
        x = nStr.split('.');
        x1 = x[0];
        x2 = x.length > 1 ? '.' + x[1] : '';
        var rgx = /(\d+)(\d{3})/;
        while (rgx.test(x1)) {
            x1 = x1.replace(rgx, '$1' + ',' + '$2');
        }
        return x1 + x2;
    }

    $(".navbar-nav .nav-item").removeClass("active");
    $("#nav-1").addClass("active");

    $(document).ready(function () {
        fn_buscar();
        $(".ui-datepicker-trigger").hide();
    });

</script>