EPROCURENTWEB/Controllers/ContactoController.cs
using EPROCUREMENT.GAPPROVEEDOR.Entities;
using EprocurementWeb.Business;
using EprocurementWeb.Filters;
using EprocurementWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EprocurementWeb.Controllers
{
    public class ContactoController : Controller
    {
        // GET: Contacto
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetContactos()
        {
            ContactoResponseDTO proveedor;
            List<ProveedorContactoDTO> contactoList = new List<ProveedorContactoDTO>();
            try
            {
                var usuarioInfo = new ValidaSession().ObtenerUsuarioSession();
                BusinessLogic businessLogic = new BusinessLogic();
                ContactoRequestDTO request = new ContactoRequestDTO();
                request.IdProveedor = usuarioInfo.IdProveedor;

                var response = businessLogic.GetContactoProveedorList(request);
                if (response.Success)
                {
                    foreach(var contacto in response.ContactoList)
                    {
                        contacto.EsPrincipal = contacto.ContactoPrincipal == 1;
                        contacto.Tipo = contacto.ContactoPrincipal == 1 ? "Principal" : "Opcional";
                    }
                    var totalPrincipal = response.ContactoList.Count(x => x.EsPrincipal);
                    ViewBag.totalPrincipal = totalPrincipal;
                    contactoList = response.ContactoList;
                }

            }
            catch (Exception ex)
            {
                return Json(new List<ProveedorContactoDTO>(), JsonRequestBehavior.AllowGet);
            }
            return Json(contactoList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult NuevoContacto()
        {
            ProveedorContactoModel contacto = new ProveedorContactoModel();
            BusinessLogic businessLogic = new BusinessLogic();
            var usuarioInfo = new ValidaSession().ObtenerUsuarioSession();
            contacto.IdProveedor = usuarioInfo.IdProveedor;
            ViewBag.ZonaHorariaList = businessLogic.GetZonaHorariaList();
            ViewBag.NacionalidadList = businessLogic.GetNacionalidadList();
            ViewBag.PaisList = businessLogic.GetPaisesList();
            return View(contacto);
        }

        public ActionResult EditarContacto(int idContacto)
        {
            ProveedorContactoModel contacto = new ProveedorContactoModel();
            BusinessLogic businessLogic = new BusinessLogic();
            ViewBag.ZonaHorariaList = businessLogic.GetZonaHorariaList();
            ViewBag.NacionalidadList = businessLogic.GetNacionalidadList();
            ViewBag.PaisList = businessLogic.GetPaisesList();

            var usuarioInfo = new ValidaSession().ObtenerUsuarioSession();
            ContactoRequestDTO request = new ContactoRequestDTO();
            request.IdProveedor = usuarioInfo.IdProveedor;
            var response = businessLogic.GetContactoProveedorList(request);
            if (response.Success)
            {
                var contactoItem = response.ContactoList.FirstOrDefault(x => x.IdContacto == idContacto);
                if (contactoItem != null)
                {
                    contacto = new ProveedorContactoModel
                    {
                        IdContacto = contactoItem.IdContacto,
                        Cargo = contactoItem.Cargo,
                        Email = contactoItem.Email,
                        Fax = contactoItem.Fax,
                        IdIdioma = contactoItem.IdIdioma,
                        IdNacionalidad = contactoItem.IdNacionalidad,
                        IdPais = contactoItem.IdPais,
                        IdProveedor = contactoItem.IdProveedor,
                        IdZonaHoraria = contactoItem.IdZonaHoraria,
                        NombreContacto = contactoItem.NombreContacto,
                        TelefonoDirecto = contactoItem.TelefonoDirecto,
                        TelefonoMovil = contactoItem.TelefonoMovil,
                        EsPrincipal = contactoItem.ContactoPrincipal > 0
                    };
                }
            }
            return View(contacto);
        }

        [HttpPost, ActionName("EditarContacto")]
        [ValidateAntiForgeryToken]
        public ActionResult EditarContacto(ProveedorContactoModel contactoItem)
        {
            try
            {
                BusinessLogic businessLogic = new BusinessLogic();
                if (ModelState.IsValid)
                {
                    ContactoRequestDTO request = new ContactoRequestDTO();
                    request.Contacto = new ProveedorContactoDTO
                    {
                        IdContacto = contactoItem.IdContacto,
                        Cargo = contactoItem.Cargo,
                        Email = contactoItem.Email,
                        Fax = contactoItem.Fax,
                        IdIdioma = contactoItem.IdIdioma,
                        IdNacionalidad = contactoItem.IdNacionalidad,
                        IdPais = contactoItem.IdPais,
                        IdProveedor = contactoItem.IdProveedor,
                        IdZonaHoraria = contactoItem.IdZonaHoraria,
                        NombreContacto = contactoItem.NombreContacto,
                        TelefonoDirecto = contactoItem.TelefonoDirecto,
                        TelefonoMovil = contactoItem.TelefonoMovil,
                        ContactoPrincipal = contactoItem.EsPrincipal ? 1 : 0
                    };
                    var response = businessLogic.UpdateContacto(request);
                    if (response.Success)
                    {
                        return Redirect("/Contacto/Index#updateSuccess");
                    }
                }
                else
                {
                    ViewBag.ZonaHorariaList = businessLogic.GetZonaHorariaList();
                    ViewBag.NacionalidadList = businessLogic.GetNacionalidadList();
                    ViewBag.PaisList = businessLogic.GetPaisesList();
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("ErrorGeneral", "Se generó un error al procesar la solicitud.");
            }

            return View(contactoItem);
        }

        [HttpPost, ActionName("NuevoContacto")]
        [ValidateAntiForgeryToken]
        public ActionResult NuevoContacto(ProveedorContactoModel contactoItem)
        {
            try
            {
                BusinessLogic businessLogic = new BusinessLogic();

                var usuarioInfo = new ValidaSession().ObtenerUsuarioSession();
                if (ModelState.IsValid)
                {
                    var correoValido = businessLogic.ValidacionCampos(new ContactoRequestDTO { Contacto = new ProveedorContactoDTO { Email = contactoItem.Email } });

                    if (correoValido)
                    {
                        ContactoRequestDTO request = new ContactoRequestDTO();
                        request.Contacto = new ProveedorContactoDTO
                        {
                            Cargo = contactoItem.Cargo,
                            Email = contactoItem.Email,
                            Fax = contactoItem.Fax,
                            IdIdioma = contactoItem.IdIdioma,
                            IdNacionalidad = contactoItem.IdNacionalidad,
                            IdPais = contactoItem.IdPais,
                            IdProveedor = usuarioInfo.IdProveedor,
                            IdZonaHoraria = contactoItem.IdZonaHoraria,
                            NombreContacto = contactoItem.NombreContacto,
                            TelefonoDirecto = contactoItem.TelefonoDirecto,
                            TelefonoMovil = contactoItem.TelefonoMovil,
                            ContactoPrincipal = contactoItem.EsPrincipal ? 1 : 0
                        };
                        var response = businessLogic.UpdateContacto(request);
                        if (response.Success)
                        {
                            return Redirect("/Contacto/Index#insertSuccess");
                        }
                    }
                    else
                    {
                        ViewBag.ZonaHorariaList = businessLogic.GetZonaHorariaList();
                        ViewBag.NacionalidadList = businessLogic.GetNacionalidadList();
                        ViewBag.PaisList = businessLogic.GetPaisesList();
                        ModelState.AddModelError("Email", "Este Email ya se encuentra registrado");
                    }                  
                }
                else
                {
                    ViewBag.ZonaHorariaList = businessLogic.GetZonaHorariaList();
                    ViewBag.NacionalidadList = businessLogic.GetNacionalidadList();
                    ViewBag.PaisList = businessLogic.GetPaisesList();
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("ErrorGeneral", "Se generó un error al procesar la solicitud.");
            }

            return View(contactoItem);
        }

        public JsonResult EliminarContacto(int idContacto)
        {
            try
            {
                BusinessLogic businessLogic = new BusinessLogic();
                var usuarioInfo = new ValidaSession().ObtenerUsuarioSession();
                ContactoRequestDTO request = new ContactoRequestDTO();
                request.Contacto = new ProveedorContactoDTO
                {
                    IdContacto = idContacto,
                    IdProveedor = usuarioInfo.IdProveedor
                };

                var response = businessLogic.DeleteContacto(request);
                if (response.Success)
                {

EPROCURENTWEB/Views/Contacto/EditarContacto.cshtml
@model EprocurementWeb.Models.ProveedorContactoModel

@{
    ViewBag.Title = "Editar Contacto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/validacionProveedor.css" rel="stylesheet" />
@using (Html.BeginForm("EditarContacto", "Contacto", FormMethod.Post))
{
    @Html.AntiForgeryToken()
<div class="row mt-4">
    <div class="col-md-12">
        <div class="accordion" id="accordionExample">
            <div class="card card-border">
                <div class="card-header" id="headingOne">
                    <span class="card-titulo">
                        Detalles del contacto
                        <button class="btn btn-link collapsed float-right" type="button" data-toggle="collapse" data-target="#detallecontacto" aria-expanded="false" aria-controls="collapseThree">
                            <i class="fas fa-chevron-up collapse-color"></i>
                        </button>
                    </span>
                </div>
                <div id="detallecontacto" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <div>
                        <div class="card-body">
                            <div class="row">
                                @Html.ValidationMessage("ErrorGeneral", new { @class = "label-formulario field-validation-error" })
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.HiddenFor(model => model.IdContacto)
                                        @Html.LabelFor(model => model.NombreContacto, new { @class = "label-formulario" })
                                        @Html.TextBoxFor(model => model.NombreContacto, new { @class = "form-control col-md-12" })
                                        @Html.ValidationMessageFor(model => model.NombreContacto, "", new { @class = "label-formulario field-validation-error" })
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Cargo, new { @class = "label-formulario" })
                                        @Html.TextBoxFor(model => model.Cargo, new { @class = "form-control col-md-12" })
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.IdNacionalidad, new { @class = "label-formulario" })
                                        @Html.DropDownListFor(model => model.IdNacionalidad, new SelectList(ViewBag.NacionalidadList, "IdNacionalidad", "Nombre"), "Selecciona", new { @class = "form-control col-md-12" })
                                        @Html.ValidationMessageFor(model => model.IdNacionalidad, "", new { @class = "label-formulario field-validation-error" })
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.TelefonoDirecto, new { @class = "label-formulario" })
                                        @Html.TextBoxFor(model => model.TelefonoDirecto, new { placeholder = "Ej. 55 1234 5678", @class = "form-control col-md-12" })
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.TelefonoMovil, new { @class = "label-formulario" })
                                        @Html.TextBoxFor(model => model.TelefonoMovil, new { placeholder = "Ej. 55 1234 5678", @class = "form-control col-md-12" })
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Fax, new { @class = "label-formulario" })
                                        @Html.TextBoxFor(model => model.Fax, new { @class = "form-control col-md-12" })
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Email, new { @class = "label-formulario" })
                                        @Html.TextBoxFor(model => model.Email, new { placeholder = "Ej. correo@dominio.com", @class = "form-control col-md-12" })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "label-formulario field-validation-error" })
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.IdPais, new { @class = "label-formulario" })
                                        @Html.DropDownListFor(model => model.IdPais, new SelectList(ViewBag.PaisList, "IdPais", "Nombre"), "Selecciona", new { @class = "form-control col-md-10" })
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.IdZonaHoraria, new { @class = "label-formulario" })
                                        @Html.DropDownListFor(model => model.IdZonaHoraria, new SelectList(ViewBag.ZonaHorariaList, "IdZonaHoraria", "Nombre"), "Selecciona", new { @class = "form-control col-md-12" })
                                        @Html.ValidationMessageFor(model => model.IdZonaHoraria, "", new { @class = "label-formulario field-validation-error" })
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        @if (Model.EsPrincipal)
                                        {
                                            <table>
                                                <tr>
                                                    <td><br /></td>
                                                </tr>
                                                <tr>
                                                    @Html.HiddenFor(model => model.EsPrincipal)
                                                    <td>@Html.CheckBoxFor(model => model.EsPrincipal, new { @class = "form-control col-md-12", @disabled = "disabled" })</td>
                                                    <td>@Html.LabelFor(model => model.ContactoPrincipal, new { @class = "label-formulario" })</td>
                                                </tr>
                                            </table>
                                        }
                                        else
                                        {
                                            <table>
                                                <tr>
                                                    <td><br /></td>
                                                </tr>
                                                <tr>
                                                    <td>@Html.CheckBoxFor(model => model.EsPrincipal, new { @class = "form-control col-md-12" })</td>
                                                    <td>@Html.LabelFor(model => model.ContactoPrincipal, new { @class = "label-formulario" })</td>
                                                </tr>
                                            </table>
                                            
                                            
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 mt-3"></div>
    <div class="col-sm-6">&nbsp;</div>
    <div class="col-sm-3">
        <a href="@Url.Action("Index", "Contacto")">
            <button class="btnStyle btnWhite" type="button">Cancelar</button>
        </a>
    </div>
    <div class="col-sm-3">
        <button class="btnStyle" type="submit">Aceptar</button>
    </div>
</div>
}

EPROCURENTWEB/Views/Contacto/Index.cshtml
@{
    ViewBag.Title = "Contactos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Gestor.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.css" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<div class="row">
    <div class="col-md-12">
        <div class="card1 mt-3">
            <div class="card-body1">
                <div class="row">
                    <div class="col-sm-10">
                        <b>Contactos</b>
                    </div>
                    <div class="col-sm-2">
                        <a href="@Url.Action("NuevoContacto", "Contacto")" class="ntb-agregarcontacto"><i class="fa fa-plus"></i> Agregar</a>
                        @*@Html.ActionLink("Agregar", "NuevoContacto", "Contacto")*@
                    </div>
                    </div>
                </div>
        </div>
    </div>
</div>
<div class="row mt-3">
    <div class="col-sm-12">
        <table id="Table"></table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        fn_consulta();

        if (window.location.hash == "#updateSuccess") {
            Swal.fire({
                position: 'middle',
                icon: 'success',
                title: '¡Modificación Exitosa!',
                html: '<p class="text">Modificación de Contacto.</p> ' +
                    '</br> <p class="text">Se actualizo la información correctamente</p>',
                showConfirmButton: true,
                timer: 3000
            })
        }

        if (window.location.hash == "#insertSuccess") {
            Swal.fire({
                position: 'middle',
                icon: 'success',
                title: '¡Registro Exitoso!',
                html: '<p class="text">Registro de Contacto.</p> ' +
                    '</br> <p class="text">Se ha registrado la información correctamente</p>',
                showConfirmButton: true,
                timer: 3000
            })
        }       

    });

    //var fn_checkbox = function (idContacto, valorChk) {
    //    valorChk = !valorChk;
    //    var jsonData = JSON.stringify({ idContacto: idContacto, principal: valorChk });
    //    Swal.fire({
    //        title: '¿Esta seguro de actualizar el contacto?',

    //        icon: 'warning',
    //        showCancelButton: true,
    //        confirmButtonColor: '#432979',
    //        cancelButtonColor: '#d33',
    //        confirmButtonText: 'Aceptar',
    //        cancelButtonText: 'Cancelar'
    //    }).then((result) => {
    //        if (result.value) {
    //            $.ajax({
    //                type: "POST",
    //                contentType: "application/json; charset=utf-8",
    //                url: "/Contacto/ActualizaPrincipal",
    //                data: jsonData,
    //                async: false,
    //                success: function (data) {
    //                    if (data) {
    //                        Swal.fire({
    //                            position: 'middle',
    //                            icon: 'success',
    //                            title: 'El contacto ha sido actualizado con éxito',
    //                            showConfirmButton: false,
    //                            timer: 1500
    //                        })
    //                        setTimeout(function () { fn_consulta();; }, 1500);
    //                    } else {
    //                        Swal.fire({
    //                            position: 'middle',
    //                            icon: 'error',
    //                            title: 'Ocurrio un error al procesar la solicitud',
    //                            showConfirmButton: false,
    //                            timer: 1500
    //                        })
    //                    }

    //                },
    //            });
    //        }
    //    })
    //}

    var fn_eliminar = function (idContacto) {
        console.log(idContacto);

            var jsonData = JSON.stringify({ idContacto: idContacto });
        Swal.fire({
            title: '¿Esta seguro de eliminar el contacto?',

            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#432979',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Aceptar',
            cancelButtonText: 'Cancelar'
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    url: "/Contacto/EliminarContacto",
                    data: jsonData,
                    async: false,
                    success: function (data) {
                        if (data) {
                            Swal.fire({
                                position: 'middle',
                                icon: 'success',
                                title: 'El contacto ha sido eliminado con éxito',
                                showConfirmButton: false,
                                timer: 1500
                            })
                            setTimeout(function () { fn_consulta();; }, 1500);
                        } else {
                            Swal.fire({
                                position: 'middle',
                                icon: 'error',
                                title: 'Ocurrio un error al procesar la solicitud',
                                showConfirmButton: false,
                                timer: 1500
                            })
                        }

                    },
                });
            }
        })
    }

    var fn_consulta = function () {
         $.ajax({
             type: "POST",
             contentType: "application/json; charset=utf-8",
             url: '@Url.Action("GetContactos", "Contacto")',
             async: false,
             success: function(data) {
                 console.log("Traigo Datos", data)
                 $("#Table").html('');
                 $("#Table").append('<thead class="bg-light-purple"><tr>' +
                     '<td>Nombre</td>' +
                     '<td>Correo Electrónico</td>' +
                     '<td>Tipo</td>' +
                     '<td>Editar</td>' +
                     '<td>Eliminar</td>' +
                     '</tr></thead>'
                 );
                 $("#Table").DataTable().clear().draw();
                 $("#Table").DataTable().destroy();

                 $("#Table").append('<tbody>');
                 //let seleccionados = data.filter(contacto => contacto.EsPrincipal);
                 for (i = 0; i < data.length; i++) {

                     var linkEdit = '@Html.ActionLink(" ", "EditarContacto", "Contacto", new { idContacto = "_idContacto_" }, new { @class = "fas fa-edit icon-color" })';
                     var btnEliminar = '<input type="button" value="x" class="BTN-DELETE-CONTACTO icon-color" onclick="fn_eliminar(_idContacto_)" />';
                     //console.log('console.log(data[i].EsPrincipal)', data[i].EsPrincipal)
                     //var chkPrincipal = '<input type="checkbox" value="_value_" onclick="fn_checkbox(_idContacto_, _EsPrincipal_)" checked/>';
                     linkEdit = linkEdit.replace('_idContacto_', data[i].IdContacto);
                     btnEliminar = btnEliminar.replace('_idContacto_', data[i].IdContacto)
                     //if (data[i].EsPrincipal) {
                     //    var chkPrincipal = '<input type="checkbox" value="_value_" onclick="fn_checkbox(_idContacto_, _EsPrincipal_)" checked/>';
                     //}
                     //else {
                     //    if (seleccionados.length != 2) {
                     //        var chkPrincipal = '<input type="checkbox" value="_value_" onclick="fn_checkbox(_idContacto_, _EsPrincipal_)" />';
                     //    } else {
                     //        var chkPrincipal = '';
                     //    }
                     //}                     
                     //chkPrincipal = chkPrincipal.replace('_idContacto_', data[i].IdContacto);
                     //chkPrincipal = chkPrincipal.replace('_EsPrincipal_', data[i].EsPrincipal);

                     if (data[i].ContactoPrincipal == 0) {
                         $("#Table").append('<tr>' +
                             '<td style="dislay: none;"><b>' + data[i].NombreContacto + '</b></td>' +
                             '<td style="dislay: none;">' + data[i].Email + '</td>' +
                             '<td style="dislay: none;">' + data[i].Tipo + '</td>' +
                             '<td style="dislay: none;"><div class="btn-circle">' + linkEdit + '</div></td>' +
                             '<td style="dislay: none;"><div >' + btnEliminar + '</div></td>' + '</tr>'
                         );
                     }
                     else {
                         $("#Table").append('<tr>' +
                             '<td style="dislay: none;"><b>' + data[i].NombreContacto + '</b></td>' +
                             '<td style="dislay: none;">' + data[i].Email + '</td>' +
                             '<td style="dislay: none;">' + data[i].Tipo + '</td>' +
                             '<td style="dislay: none;"><div class="btn-circle">' + linkEdit + '</div></td>' +
                             '<td style="dislay: none;"><div ></div></td>' + '</tr>'
                         );
                     }
                 }
                 $("#Table").append('</tbody>');

                 $('#Table').DataTable({
                        "paging": false,
                         "bScrollInfinite": true,
                         "bScrollCollapse": true
                     });

             },
         });
        }
</script>